version: '2'
services:
  recipe_db:
    image: postgres
    container_name: recipe_db
    volumes:
      - "recipe_data:/var/lib/postgresql/data"
  web:
    build:
      context: ./web
      args:
        env: dev
    command: "python manage.py collectstatic --noinput; python manage.py runserver 0.0.0.0:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.dev
    volumes: 
      - ./web:/app
      - ./static:/static
      - ./media:/media
    depends_on:
      - recipe_db
    ports:
      - "8000:8000"

volumes:
  recipe_data:
